import { MFOData } from './MFOCard';

export const mfoList: MFOData[] = [
  {
    name: "Cashiro",
    logo: "https://cdn.poehali.dev/files/86b23edf-41f5-4981-9f6f-8903359e833a.png",
    subtitle: "Микрозайм",
    amount: "1-30 тыс ₽",
    rate: "0,8% в день",
    term: "3-30 дней",
    iconName: "Zap",
    iconText: "Быстрое одобрение",
    url: "https://trk.ppdu.ru/click/txUVt02X?erid=LjN8K2yaa",
    borderColor: "border-gray-200",
    bgColor: "bg-red-500",
    textColor: "text-red-700",
    buttonColor: "bg-red-600",
    buttonHoverColor: "hover:bg-red-700"
  },
  {
    name: "ЗАЁМ.РУ",
    logo: "https://cdn.poehali.dev/files/2015ac3c-f2ce-498f-b8ca-ba19525a1ece.png",
    subtitle: "Микрозайм",
    amount: "31-100 тыс ₽",
    rate: "0,4-0,6% в день",
    term: "1-365 дней",
    iconName: "TrendingUp",
    iconText: "Крупные суммы",
    url: "https://trk.ppdu.ru/click/HHvfTe22?erid=2SDnjcjAe4z",
    borderColor: "border-blue-200",
    bgColor: "bg-blue-500",
    textColor: "text-blue-700",
    buttonColor: "bg-blue-600",
    buttonHoverColor: "hover:bg-blue-700"
  },
  {
    name: "А Деньги",
    logo: "https://cdn.poehali.dev/files/906f071c-dfe6-42b2-a87a-71e0b47cf4ba.png",
    subtitle: "Микрозайм",
    amount: "до 30 тыс ₽",
    term: "до 30 дней",
    feature: "Особенности",
    featureValue: "Автопродление",
    iconName: "Shield",
    iconText: "Без поручителей",
    url: "https://trk.ppdu.ru/click/amxPDOWZ?erid=LjN8KSUm6",
    borderColor: "border-orange-200",
    bgColor: "bg-orange-500",
    textColor: "text-orange-700",
    buttonColor: "bg-orange-600",
    buttonHoverColor: "hover:bg-orange-700"
  },
  {
    name: "Срочно деньги",
    logo: "https://cdn.poehali.dev/files/fde66a38-b113-4cea-88c9-400bc074a896.png",
    subtitle: "Микрозайм",
    amount: "2-30 тыс ₽",
    rate: "0-0,8% в день",
    term: "1-30 дней",
    iconName: "Clock",
    iconText: "Решение за 1 минуту",
    url: "https://trk.ppdu.ru/click/QBskke4v?erid=2SDnjdmVzVA&siteId=8015",
    borderColor: "border-lime-200",
    bgColor: "bg-lime-500",
    textColor: "text-lime-700",
    buttonColor: "bg-lime-600",
    buttonHoverColor: "hover:bg-lime-700"
  },
  {
    name: "ДеньгиОК",
    logo: "https://cdn.poehali.dev/files/bb9beedc-24f3-45b4-9072-dc26109891c9.png",
    subtitle: "Микрозайм",
    amount: "2-20 тыс ₽",
    rate: "0,8% в день",
    term: "10-15 дней",
    iconName: "CheckCircle",
    iconText: "Надёжный МФО",
    url: "https://trk.ppdu.ru/click/5IMsM4AM?erid=2SDnjbrUYhH",
    borderColor: "border-green-200",
    bgColor: "bg-green-500",
    textColor: "text-green-700",
    buttonColor: "bg-green-600",
    buttonHoverColor: "hover:bg-green-700"
  },
  {
    name: "495 Кредит",
    logo: "https://cdn.poehali.dev/files/30e7548b-ceaa-48bf-9af0-09112e00e06a.png",
    subtitle: "Микрозайм",
    amount: "2-20 тыс ₽",
    rate: "0,8% в день",
    term: "10-15 дней",
    iconName: "Star",
    iconText: "Проверенный МФО",
    url: "https://trk.ppdu.ru/click/iTsTuS3a?erid=2SDnjcVZcGM",
    borderColor: "border-purple-200",
    bgColor: "bg-purple-500",
    textColor: "text-purple-700",
    buttonColor: "bg-purple-600",
    buttonHoverColor: "hover:bg-purple-700"
  },
  {
    name: "Ваш кредит",
    logo: "https://cdn.poehali.dev/files/ca8e3d92-1c16-4d07-9efd-dd3dd355c986.png",
    subtitle: "Микрозайм",
    amount: "2-30 тыс ₽",
    term: "до 30 дней",
    feature: "Особенности",
    featureValue: "Первый бесплатно",
    iconName: "Gift",
    iconText: "Бесплатно до 7 дней",
    url: "https://trk.ppdu.ru/click/zo5OCU1U?erid=2SDnjdPMs5P",
    borderColor: "border-green-200",
    bgColor: "bg-green-500",
    textColor: "text-green-700",
    buttonColor: "bg-green-600",
    buttonHoverColor: "hover:bg-green-700"
  },
  {
    name: "Свои люди",
    logo: "https://cdn.poehali.dev/files/7add6f84-4026-4d23-9945-7d786f04deec.png",
    subtitle: "Микрозайм",
    amount: "3-30 тыс ₽",
    rate: "0,8% в день",
    term: "5-30 дней",
    iconName: "Users",
    iconText: "Семейный МФО",
    url: "https://trk.ppdu.ru/click/qNnv8jjF?erid=LjN8KMSTi",
    borderColor: "border-blue-200",
    bgColor: "bg-blue-500",
    textColor: "text-blue-700",
    buttonColor: "bg-blue-600",
    buttonHoverColor: "hover:bg-blue-700"
  },
  {
    name: "Небус",
    logo: "https://cdn.poehali.dev/files/efebe482-4753-45e8-9a62-23b3f50cb92d.png",
    subtitle: "Микрозайм",
    amount: "7-100 тыс ₽",
    rate: "0,48-0,8% в день",
    term: "7 000 ₽",
    feature: "Минимум",
    iconName: "TrendingUp",
    iconText: "Крупные займы",
    url: "https://trk.ppdu.ru/click/PdOUQvMM?erid=2SDnjck7R1e",
    borderColor: "border-cyan-200",
    bgColor: "bg-cyan-500",
    textColor: "text-cyan-700",
    buttonColor: "bg-cyan-600",
    buttonHoverColor: "hover:bg-cyan-700"
  },
  {
    name: "ДоброЗайм",
    logo: "https://cdn.poehali.dev/files/e574ae63-8ff5-48a4-9743-8037a99e6035.png",
    subtitle: "Микрозайм",
    amount: "1-200 тыс ₽",
    rate: "0-0,8% в день",
    term: "3-378 дней",
    iconName: "Heart",
    iconText: "Максимальные суммы",
    url: "https://trk.ppdu.ru/click/8ec0Cird?erid=LjN8JvgqW",
    borderColor: "border-emerald-200",
    bgColor: "bg-emerald-500",
    textColor: "text-emerald-700",
    buttonColor: "bg-emerald-600",
    buttonHoverColor: "hover:bg-emerald-700"
  }
];